### ISSUE TITLE
MyDealz Beitrag

### ISSUE THREAD

**Issue by TheKushStyle** [Spegeli/DealReminder#1]
Dein Beitrag wurde ja "gelöscht/als Spam gemeldet" und ist nicht mehr sichtbar. Geht es hier trotzdem weiter oder ist das Projekt gestorben ?

**Comment by Spegeli** [comment]
Ja wurde von MyDealz gelöscht, hier geht es aber trotzdem weiter.
Werde in den nächsten 1-2 Tagen das ganze hier übersichtlicher gestalten.
