### ISSUE TITLE
Platfform

### ISSUE THREAD

**Issue by blautob** [Spegeli/DealReminder#2]
Bin auch schon sehr gespannt! Auf welche Plattform wird das Ding den Laufen WIN/Mac oder Linux?

**Comment by amuessig** [comment]
Naja, so wie ich das sehe ist das PHP mit einer MySQL Datenbank dahinter.. Läuft also auf jedem System.

**Comment by Spegeli** [comment]
Richtig PHP & MySQL war das ursprüngliche Projekt, aber mit C# geht es für mich irgendwie schneller ^^

Also erstellt wird das Programm auf Windows und da ich noch nie etwas mit Entwicklung unter Mac & Linux zu tun hatte kann es vorkommen das es unter Mac & Linux evtl. nicht (richtig) funktioniert da es doch die ein oder andere Funktion gibt die zwischen Win, Mac & Linux unterschiedlich ist.

Aber das werden wir sehen wenn es fertig ist ;-)

**Comment by blautob** [comment]
Ok. Veröffentlichst du dann die Source und man kann es dann für Linux compilieren. Bin da leider nicht so bewandert.
Ich hoffte dass man das 24/7 auf einem raspberry laufen lassen könnte.
