### ISSUE TITLE
Alpha V1.0.1

### ISSUE THREAD

**Issue by Spegeli** [Spegeli/DealReminder#3]
Servus liebe Leute,
das Programm ist noch nicht fertig, allerdings möchte ich euch jetzt schon mal eine erste Alpha Version vorstellen:

**Download:** http://www55.zippyshare.com/v/HNZYsUvS/file.html
**VirusTotal:** https://www.virustotal.com/de/file/703710e916bd7b3ff8866cb30a1b000c3ebd0ae3109174985110226e9e3c5ffc/analysis/1483811857/

**Anleitung:**
- DealReminder.exe starten
- Für den Login benötigt ihr den Userkey "**Free**" (ohne Anführungszeichen).
- Unter "**Produkt Datenbank**" tragt ihr die ASIN der Produkte ein welche er Überwachen soll.
 - - Die ASIN ist 10 Stellig, hat folgendes Format "B00YUIM2J0" und findet ihr in der URL des Amazon Produktes 
 - - Löschen könnt ihr einen Eintrag in dem ihr in das erste Leere Feld klickt und somit die ganze Zeile Markiert wird und anschließend auf Entfernen klickt. Mehrfach Auswahl ist möglich.
- Dann geht ihr in den "**Crawler**" Tab und klickt den Start Knopf.
 - - Nach dem ihr den Start Knopf gedrückt habt beginnt das Programm ein Produkt nach dem anderen zu Aktualisieren.
 - - Zwischen jeder Produkt Abfrage vergehen (aktuell) 30-40 Sekunden.
 - - Sobald ein Produkt Aktualisiert wurde seht ihr die aktuellen Daten ebenfalls in dem "Produkt Datenbank" Tab.
 - - Der Start Knopf ändert sich aktuell noch nicht in einen Stop Knopf, ihr werdet per Pop-Up Benachrichtigt wenn der Durchlauf Fertig ist.

Das war es auch schon mit den Funktionen der Alpha V1.0.
In der nächsten Version kommt dann der Erinnerungs Tab wo ihr die Erinnerungen inkl. Benachrichtigung Einstellen könnt.

Wenn ihr die Alpha V1.0 ausprobiert habt lasst mich doch bitte wissen ob sie bei euch soweit funktioniert hat ;-)

**Comment by blautob** [comment]
Klasse bin gespannt aufs Testen!

**Comment by blautob** [comment]
Bekomme unter WinXP VM die Fehlermeldung DealReminder.exe ist keine zulässige Win32-Anwendung

**Comment by Spegeli** [comment]
Ok muss ich mal schauen. Hab das ganze unter Windows 10 Entwickelt.

**Comment by amuessig** [comment]
Man nutzt auch kein Windows XP mehr. Schon aus Sicherheitsgründen.

**Comment by Spegeli** [comment]
**Nicht wundern liebe Leute das Projekt ist nicht Tot, allerdings habe ich es Zeitlich noch nicht geschafft weiter zu machen.
Und jetzt stehen Feiertage und Geburtstage vor der Tür, daher werde ich es wohl erst Anfang Januar fertig stellen können.

Mfg**

**Comment by mySebbe** [comment]
Tolle Arbeit! Weiter so!

Viele Gr??e
Sebastian

________________________________

**Comment by Spegeli** [comment]
Hab jetzt gerade Version 1.0.1 hochgeladen (und im ersten Beitrag aktualisiert).
Die Version 1 funktioniert nicht mehr da ich den Login auf SSL Verbindung umgestellt habe.

Zudem werden die ShortURLs jetzt nicht mehr über bit.ly geshortet, sonder über meinen eigenen ShortURL Service: https://shorturl.spegeli.de/

**Comment by Toddehawk** [comment]
Warum bekomm ich eine VIREN-Meldung?

Causal Event: VirusHttpEvent
{
   "nodeName": "virus_blocker",
   "timeStamp": "2017-01-08 10:01:06.876",
   "virusName": "Gen:Variant.MSILPerseus.63420",
   "requestId": 96926427183455,
   "clean": false
}

**Comment by Spegeli** [comment]
Habe jetzt in den letzten Tagen folgendes gemacht:


- Beim Programm Start wird jetzt kontrolliert ob "SQL Server 2016 Express LocalDB" Installiert. Ohne dies kommt es wohl zu einem Crash da er dann nicht mit der Datenbank arbeiten kann.
- - http://i.epvpimg.com/oxc9f.png
- 4 weitere ShortURL Service hinzugefügt. Über die Einstellungen kann dann jeder selber entscheiden welchen er benutzen möchte.

**Comment by Spegeli** [comment]
Hab mich heute im Internet etwas über die rechtliche Grundlage bzw. des Scraping informiert.
Scheint das es im Fall meines Programms erlaubt ist bzw. Eine Grauzone.

Daher habe ich mich entschieden das ganze jetzt wirklich weiter zu Entwickeln und habe daher die Domain "www.DealReminder.de" registriert.

Der Login, Downloads usw. werden dann direkt von dieser Domain erfolgen.
Zudem werde ich dann mal ne kleine Website machen wo Leute ihren eigenen User key Generieren können.

:-)

**Comment by Spegeli** [comment]
Hab jetzt gerade die Dateien auf die neue Domain (www.DealReminder.de) übertragen.
Mit der nächsten Version wird die alte Version nicht mehr funktionieren da ich dann die alte Domain welche bisher für den Login zuständig ist nicht mehr aktiv ist.

Zudem hab ich am PreStart Fenster (welches erscheint wenn es Probleme mit dem Programm Start gibt) etwas weiter gemacht: http://i.epvpimg.com/l8iGg.png
Per Icon ist jetzt Sichtbar ob wo der Fehler liegt. Die Optionen für die Datenbank baue ich morgen ein.

Zudem habe ich das Login Fenster etwas geändert: http://i.epvpimg.com/2Rfob.png
Enthält dann auch einen Link zur Website wo man in Zukunft seinen eigenen UserKey erstellen kann.

Sobald alle Funktionen für das PreStart Fenster fertig sind (1-2 Tage) baue ich noch eine Funktion ein welche beim Programm Start auf Updates checkt und den User dann Informiert (in Zukunft dann evtl. auch mit Auto-Update Funktion).

**Comment by blautob** [comment]
Das Teil nimmt ja mittlerweile ganz schön große Dimensionen an.
Was hat es denn mit dem Userkey,Login auf sich?
Wird denn irgendwann die Source geteilt um das Teil headless auf Linux zu betreiben?

**Comment by Spegeli** [comment]
Den UserKey braucht man einfach zum Einloggen. 
So hab ich etwas die Controller über die Benutzung der App und könnte sie bei bedarf abschalten.
Aktuell können alle den Userkey "Free" benutzen, in den nächsten Tagen wird jeder seinen eigenen Generieren können.

Bisher ist nicht geplant das ding OpenSource zu machen. 
Bzgl. Linux Support kann ich erst mehr sagen wenn die Windows Version fertig ist.

**Comment by Spegeli** [comment]
Hab mich die letzten 1-2 Tage mit Wordpress befasst um die neue Website aufsetzen zu können.
Hab jetzt gerade etwas Geld springen lassen und folgendes Theme gekauft: https://themeforest.net/item/avada-responsive-multipurpose-theme/2833226

Werde jetzt damit beginnen die Website aufzusetzen welche dann auch ein Forum usw. beinhalten wird.
Sobald die Website fertig ist wird alles nur noch darüber ablaufen (und nicht mehr GitHub).

Mfg

**Comment by Spegeli** [comment]
Hab jetzt heute die Update Funktion eingebaut: http://i.epvpimg.com/uJXig.png

**Comment by Spegeli** [comment]
Die Website macht gute Fortschritte und sollte in den kommenden Tagen Online gehen.
Aktuell bin ich noch auf der suche nach einem Logo: http://i.epvpimg.com/uixsf.png
Mal schauen für welches ich mich entscheiden werde ;-)

**Comment by Spegeli** [comment]
Hab mich jetzt für folgendes Logo entschieden: http://i.epvpimg.com/vM1Pd.png
Programm macht gute Fortschritte und die Website auch ;-)

**Comment by Spegeli** [comment]
Und wieder mal ein kleines Update:

* Das Logo ist jetzt im Login: http://i.epvpimg.com/kEKVc.png
* *Wird evtl. noch etwas von der größe her angepasst
